server:
  port: 8585
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/bbs?minimumIdle=2
    username: postgres
    password: 123456
    hikari:
      minimumIdle: 2
      maximumPoolSize: 4
    jpa:
      show-sql: true
      open-in-view: false
  management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: '*'
  security:
    jwt:
      role:
        locations: otus_pro
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:5443/realms/otus_pro_final
#      client:
#        registration:
#          keycloak:
#            client-id: otus_pro
#            client-secret: 01Alfe3m1Pzm9fqbvrgJIgIyPZNcygt8
#            authorization-grant-type: authorization_code
#            scope: openid-connect
#        provider:
#          keycloak:
#            issuer-uri: http://host.docker.internal:5443/realms/otus_pro_final
#            user-name-attribute: preferred_username
logging:
  level:
    org:
      springframework:
        security: TRACE

response:
  exceptions:
    needStack: false

authorization:
  jwt: false
  basic:
    user: manager
    password: 123456