services:
  db:
    container_name: otus-final-postgres
    image: postgres:16.3-alpine3.20
    ports:
      - "5450:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/01.sql
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 3
    networks:
      - otus-final-network
    profiles: ["db"]

#  db-keycloak:
#    container_name: otus-final-keycloak-postgres
#    image: postgres:16.3-alpine3.20
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_DB=keycloak
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=123456
#    volumes:
#      - db_keycloak_data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready", "-q", "-U", "postgres" ]
#      interval: 5s
#      timeout: 1s
#      retries: 3
#    networks:
#      - otus-final-network
#    profiles: [ "db" ]

  keycloak:
    container_name: otus-final-keycloak
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
      - --import-realm
    ports:
      - 5443:8080
    environment:
      - KC_HOSTNAME=localhost
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB=postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=123456
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=./otus_pro_final-realm.json
    depends_on:
      - db
    networks:
      - otus-final-network
    profiles: [ "keycloak" ]

networks:
  otus-final-network:
    name: otus-final-network

volumes:
  db_keycloak_data:
  db_data:
  db_data2:
