-- public.bulletin_boards определение

-- Drop table

-- DROP TABLE public.bulletin_boards;

CREATE TABLE public.bulletin_boards (
	disabled bool NOT NULL,
	create_date timestamp(6) NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	update_date timestamp(6) NOT NULL,
	creator varchar(255) NOT NULL,
	description varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT bulletin_boards_pkey PRIMARY KEY (id)
);