-- public.bulletins определение

-- Drop table

-- DROP TABLE public.bulletins;

CREATE TABLE public.bulletins (
	board_id int8 NOT NULL,
	create_date timestamp(6) NOT NULL,
	end_date timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	start_date timestamp(6) NULL,
	update_date timestamp(6) NOT NULL,
	"content" varchar(255) NOT NULL,
	creator varchar(255) NOT NULL,
	email varchar(255) NULL,
	phone varchar(255) NULL,
	site varchar(255) NULL,
	title varchar(255) NOT NULL,
	CONSTRAINT bulletins_pkey PRIMARY KEY (id)
);


-- public.bulletins внешние включи

ALTER TABLE public.bulletins ADD CONSTRAINT fkr1nv84mfgvoi1qxqpmtfvar2q FOREIGN KEY (board_id) REFERENCES public.bulletin_boards(id);